import Foundation

// MARK: - PodcastTranscriptLine

/// A single timed transcript paragraph for a podcast episode.
///
/// YouTube's caption track is segmented for subtitles (a few words per cue), so
/// consecutive cues are merged into readable paragraphs before display — see
/// ``PodcastTranscriptParser``.
struct PodcastTranscriptLine: Identifiable, Equatable, Sendable {
    let id: UUID
    /// Timestamp in milliseconds when this paragraph starts.
    let timeInMs: Int
    /// Duration in milliseconds covered by this paragraph.
    let durationMs: Int
    /// The transcript text for this paragraph.
    let text: String

    init(timeInMs: Int, durationMs: Int, text: String) {
        self.id = UUID()
        self.timeInMs = timeInMs
        self.durationMs = durationMs
        self.text = text
    }

    /// Timestamp in milliseconds when this paragraph ends.
    var endTimeInMs: Int {
        self.timeInMs + self.durationMs
    }
}

// MARK: - PodcastTranscript

/// A timed transcript for a podcast episode, sourced from YouTube's caption track.
struct PodcastTranscript: Equatable, Sendable {
    /// Transcript paragraphs in playback order.
    let lines: [PodcastTranscriptLine]

    /// Language code reported by the caption track (for example `"en"`).
    let languageCode: String?

    /// Whether the text comes from YouTube's auto-generated caption track.
    let isAutoGenerated: Bool

    /// An empty transcript for episodes without a caption track.
    static let unavailable = PodcastTranscript(lines: [], languageCode: nil, isAutoGenerated: false)

    /// Whether the transcript has any displayable text.
    var isAvailable: Bool {
        !self.lines.isEmpty
    }

    /// Position of a line relative to the current playback time.
    enum LineStatus: Equatable {
        case previous
        case current
        case upcoming
    }

    func lineStatuses(at timeMs: Int) -> [LineStatus] {
        self.lines.map { line in
            if line.timeInMs > timeMs {
                return .upcoming
            }
            if timeMs - line.timeInMs >= line.durationMs, line.durationMs > 0 {
                return .previous
            }
            return .current
        }
    }

    /// Index of the paragraph being spoken at `timeMs` (milliseconds), if any.
    func currentLineIndex(atMilliseconds timeMs: Int) -> Int? {
        self.lineStatuses(at: timeMs).lastIndex(of: .current)
    }
}
