import Foundation
@testable import Kaset
import Testing

// MARK: - PodcastTranscriptParserTests

@Suite(.tags(.service))
@MainActor
struct PodcastTranscriptParserTests {
    // MARK: - Caption tracks

    @Test("caption tracks are read from a player response")
    func parsesCaptionTracks() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)

        #expect(tracks.count == 3)
        #expect(tracks[0].languageCode == "de")
        #expect(tracks[0].isAutoGenerated == false)
        #expect(tracks[0].name == "Deutsch")
        #expect(tracks[0].baseURL?.absoluteString.contains("fmt=srv3") == true)
        #expect(tracks[2].languageCode == "en")
        #expect(tracks[2].isAutoGenerated)
        #expect(tracks[2].name == "English (auto-generated)")
    }

    @Test("player responses without captions yield no tracks")
    func missingCaptionsYieldNoTracks() {
        #expect(PodcastTranscriptParser.parseCaptionTracks(from: [:]).isEmpty)
        #expect(PodcastTranscriptParser.parseCaptionTracks(from: ["videoDetails": [:]]).isEmpty)
    }

    @Test("track selection prefers the requested language")
    func selectionPrefersRequestedLanguage() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)

        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "en")?.languageCode == "en")
        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "EN")?.languageCode == "en")
    }

    @Test("track selection prefers a manual track over the auto-generated one")
    func selectionPrefersManualTrack() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)

        // Both German tracks exist; the auto-generated one is listed second.
        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "de")?.isAutoGenerated == false)
    }

    @Test("track selection falls back to English, then to the first track")
    func selectionFallsBack() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)
        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "fr")?.languageCode == "en")

        let germanOnly = [tracks[0]]
        #expect(PodcastTranscriptParser.selectTrack(germanOnly, preferredLanguageCode: "fr")?.languageCode == "de")
    }

    // MARK: - Timed text URL

    @Test("the timed text URL replaces the track's own format")
    func timedTextURLReplacesFormat() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)
        let url = PodcastTranscriptParser.timedTextURL(for: tracks[0])

        #expect(url?.absoluteString.contains("fmt=srv3") == false)
        #expect(url?.absoluteString.contains("fmt=json3") == true)
        // Unrelated query parameters survive.
        #expect(url?.absoluteString.contains("caps=asr") == true)
        #expect(url?.absoluteString.contains("lang=de") == true)
    }

    // MARK: - Timed text payload

    @Test("timed text events become caption segments")
    func parsesTimedTextSegments() {
        let segments = PodcastTranscriptParser.parseTimedTextJSON(Self.timedTextJSON)

        #expect(segments.count == 2)
        #expect(segments[0].startMs == 0)
        #expect(segments[0].durationMs == 2000)
        #expect(segments[0].text == "This is the first\nparagraph of the episode.")
        // Events that only carry a line break are dropped.
        #expect(segments.allSatisfy { !$0.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty })
    }

    @Test("malformed timed text yields no segments")
    func malformedTimedTextYieldsNoSegments() {
        #expect(PodcastTranscriptParser.parseTimedTextJSON(Data("not json".utf8)).isEmpty)
    }

    // MARK: - Paragraph merging

    @Test("continuous cues are merged into one paragraph")
    func mergesContinuousCues() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 2000, text: "Hello and"),
            .init(startMs: 2000, durationMs: 2000, text: "welcome back"),
            .init(startMs: 4000, durationMs: 2000, text: "to the show."),
        ])

        #expect(lines.count == 1)
        #expect(lines[0].text == "Hello and welcome back to the show.")
        #expect(lines[0].timeInMs == 0)
        #expect(lines[0].durationMs == 6000)
    }

    @Test("a long silence starts a new paragraph")
    func longSilenceStartsNewParagraph() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 2000, text: "First thought."),
            .init(startMs: 5000, durationMs: 2000, text: "Second thought."),
        ])

        #expect(lines.count == 2)
        #expect(lines[0].text == "First thought.")
        #expect(lines[1].text == "Second thought.")
        #expect(lines[1].timeInMs == 5000)
    }

    @Test("long text is broken into several paragraphs")
    func longTextIsBrokenUp() {
        let cues = (0 ..< 20).map { index in
            PodcastTranscriptParser.Segment(
                startMs: index * 2000,
                durationMs: 2000,
                text: String(repeating: "word ", count: 10)
            )
        }

        let lines = PodcastTranscriptParser.mergeParagraphs(from: cues)

        #expect(lines.count > 1)
        #expect(lines.allSatisfy { !$0.text.isEmpty })
        // Cues are never split, so a paragraph can pass the ceiling by one cue (50 characters).
        #expect(lines.allSatisfy { $0.text.count <= 470 })
    }

    @Test("blank cues are ignored")
    func blankCuesAreIgnored() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 1000, text: "   "),
            .init(startMs: 1000, durationMs: 1000, text: "\n"),
            .init(startMs: 2000, durationMs: 1000, text: "Real text."),
        ])

        #expect(lines.count == 1)
        #expect(lines[0].text == "Real text.")
        #expect(lines[0].timeInMs == 2000)
    }

    @Test("caption line breaks collapse into spaces")
    func captionLineBreaksCollapse() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 1000, text: "one\ntwo   three"),
        ])

        #expect(lines[0].text == "one two three")
    }

    // MARK: - Transcript lookup

    @Test("the current paragraph follows playback position")
    func currentParagraphFollowsPlayback() {
        let transcript = PodcastTranscript(lines: [
            .init(timeInMs: 0, durationMs: 5000, text: "First"),
            .init(timeInMs: 5000, durationMs: 5000, text: "Second"),
            .init(timeInMs: 10000, durationMs: 5000, text: "Third"),
        ], languageCode: "en", isAutoGenerated: true)

        #expect(transcript.currentLineIndex(atMilliseconds: 0) == 0)
        #expect(transcript.currentLineIndex(atMilliseconds: 4900) == 0)
        #expect(transcript.currentLineIndex(atMilliseconds: 5000) == 1)
        #expect(transcript.currentLineIndex(atMilliseconds: 12000) == 2)
        #expect(transcript.currentLineIndex(atMilliseconds: 20000) == nil)
        #expect(transcript.lineStatuses(at: 7000) == [.previous, .current, .upcoming])
    }

    @Test("an empty transcript is unavailable")
    func emptyTranscriptIsUnavailable() {
        #expect(PodcastTranscript.unavailable.isAvailable == false)
        #expect(PodcastTranscript.unavailable.currentLineIndex(atMilliseconds: 0) == nil)
    }

    // MARK: - Chapters

    @Test("timestamped description lines become chapters")
    func parsesDescriptionChapters() {
        let chapters = PodcastTranscriptParser.parseChapters(fromDescription: Self.chapteredDescription)

        #expect(chapters.count == 4)
        #expect(chapters[0].title == "Intro")
        #expect(chapters[0].startTimeMs == 0)
        #expect(chapters[1].title == "Spending Your 5-9 Wrong")
        #expect(chapters[1].startTimeMs == 79_000)
        #expect(chapters[3].title == "Finale")
        #expect(chapters[3].startTimeMs == 3_723_000)
    }

    @Test("chapters are read from the player response description")
    func parsesChaptersFromPlayerResponse() {
        let chapters = PodcastTranscriptParser.parseChapters(from: [
            "videoDetails": [
                "shortDescription": Self.chapteredDescription,
                "lengthSeconds": "4000",
            ],
        ])

        #expect(chapters.count == 4)
        #expect(PodcastTranscriptParser.parseChapters(from: [:]).isEmpty)
        #expect(PodcastTranscriptParser.parseChapters(from: ["videoDetails": [:]]).isEmpty)
    }

    @Test("a description without three chapters is not chaptered")
    func rejectsShortChapterLists() {
        let twoChapters = "00:00 Intro\n01:19 Second Part"
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: twoChapters).isEmpty)

        // Heavily timestamped prose is likewise not a chapter list.
        let timestampsInProse = "Some thoughts from 0:00 to 1:00 about a topic."
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: timestampsInProse).isEmpty)
    }

    @Test("chapters must start at zero, ascend and stay ten seconds apart")
    func appliesYouTubeChapterRules() {
        let lateStart = "00:10 Intro\n01:19 Second\n04:12 Third"
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: lateStart).isEmpty)

        let tooClose = "00:00 Intro\n00:05 Second\n00:10 Third"
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: tooClose).isEmpty)

        let outOfOrder = "00:00 Intro\n01:00 Second\n00:30 Third"
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: outOfOrder).isEmpty)
    }

    @Test("a chapter past the end of the episode invalidates the set")
    func rejectsChaptersBeyondDuration() {
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: Self.chapteredDescription, durationSeconds: 1800).isEmpty)
        #expect(PodcastTranscriptParser.parseChapters(fromDescription: Self.chapteredDescription, durationSeconds: 4000).count == 4)
    }

    @Test("only lines that start with a timestamp and a heading are chapters")
    func parsesTimestampedLines() {
        #expect(PodcastTranscriptParser.timestampedLine("00:00 Intro")?.startMs == 0)
        #expect(PodcastTranscriptParser.timestampedLine("01:19 Second Part")?.startMs == 79_000)
        #expect(PodcastTranscriptParser.timestampedLine("1:02:03 Q&A")?.startMs == 3_723_000)

        #expect(PodcastTranscriptParser.timestampedLine("12:34") == nil)
        #expect(PodcastTranscriptParser.timestampedLine("See 12:34 for details") == nil)
        #expect(PodcastTranscriptParser.timestampedLine("00:00:00") == nil)
        #expect(PodcastTranscriptParser.timestampedLine("Plain text") == nil)
        #expect(PodcastTranscriptParser.timestampedLine("00:75 Too many seconds") == nil)
    }

    // MARK: - Fixtures

    private static let chapteredDescription = """
    Welcome back to the show!

    00:00 Intro
    01:19 Spending Your 5-9 Wrong
    04:12 Shift #1: Change Your First Habit After Work
    1:02:03 Finale

    Follow us for more.
    """

    private static let playerResponse: [String: Any] = [
        "captions": [
            "playerCaptionsTracklistRenderer": [
                "captionTracks": [
                    [
                        "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&caps=asr&lang=de&fmt=srv3",
                        "languageCode": "de",
                        "name": ["runs": [["text": "Deutsch"]]],
                    ],
                    [
                        "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&caps=asr&lang=de&fmt=srv3",
                        "languageCode": "de",
                        "kind": "asr",
                    ],
                    [
                        "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&caps=asr&lang=en&fmt=srv3",
                        "languageCode": "en",
                        "kind": "asr",
                        "name": ["runs": [["text": "English (auto-generated)"]]],
                    ],
                ],
            ],
        ],
    ]

    private static let timedTextJSON = Data(
        """
        {
          "events": [
            {
              "tStartMs": 0,
              "dDurationMs": 2000,
              "segs": [{"utf8": "This is the first\\n"}, {"utf8": "paragraph of the episode."}]
            },
            {
              "tStartMs": 2100,
              "dDurationMs": 100,
              "segs": [{"utf8": "\\n"}]
            },
            {
              "tStartMs": 2200,
              "dDurationMs": 2000,
              "segs": [{"utf8": "And a second one."}]
            }
          ]
        }
        """.utf8
    )
}

// MARK: - PodcastTranscriptSectionTests

@Suite(.tags(.service))
struct PodcastTranscriptSectionTests {
    @Test("a chapter owns the paragraphs until the next chapter starts")
    func chaptersOwnTheirParagraphs() {
        let sections = PodcastTranscriptSection.sections(
            chapters: [PodcastChapter(title: "Intro", startTimeMs: 0), PodcastChapter(title: "Second", startTimeMs: 100_000)],
            lines: [
                .init(timeInMs: 0, durationMs: 5000, text: "First"),
                .init(timeInMs: 30_000, durationMs: 5000, text: "Second"),
                .init(timeInMs: 100_000, durationMs: 5000, text: "Third"),
                .init(timeInMs: 200_000, durationMs: 5000, text: "Fourth"),
            ]
        )

        #expect(sections.count == 2)
        #expect(sections[0].chapter?.title == "Intro")
        #expect(sections[0].id == 0)
        #expect(sections[0].rows.count == 2)
        #expect(sections[1].chapter?.title == "Second")
        #expect(sections[1].id == 100_000)
        #expect(sections[1].rows.count == 2)
        // Row identity stays the paragraph's own id, which is what the transcript scrolls to.
        #expect(sections[0].rows[0].id == sections[0].rows[0].line.id)
        #expect(sections[1].rows[0].lineIndex == 2)
    }

    @Test("without chapters every paragraph sits in one section")
    func withoutChaptersThereIsOneSection() {
        let lines: [PodcastTranscriptLine] = [
            .init(timeInMs: 0, durationMs: 5000, text: "First"),
            .init(timeInMs: 5000, durationMs: 5000, text: "Second"),
        ]

        let sections = PodcastTranscriptSection.sections(chapters: [], lines: lines)

        #expect(sections.count == 1)
        #expect(sections[0].chapter == nil)
        #expect(sections[0].rows.map(\.lineIndex) == [0, 1])
    }

    @Test("paragraphs ahead of the first chapter keep their own section")
    func leadingParagraphsAreKept() {
        let sections = PodcastTranscriptSection.sections(
            chapters: [
                PodcastChapter(title: "Intro", startTimeMs: 60_000),
                PodcastChapter(title: "Second", startTimeMs: 120_000),
            ],
            lines: [
                .init(timeInMs: 0, durationMs: 5000, text: "Cold open"),
                .init(timeInMs: 60_000, durationMs: 5000, text: "Intro text"),
                .init(timeInMs: 120_000, durationMs: 5000, text: "Second text"),
            ]
        )

        #expect(sections.count == 3)
        #expect(sections[0].chapter == nil)
        #expect(sections[0].rows.map(\.lineIndex) == [0])
        #expect(sections[1].rows.map(\.lineIndex) == [1])
        #expect(sections[2].rows.map(\.lineIndex) == [2])
    }

    @Test("a chapter without paragraphs still gets a section")
    func emptyChaptersAreKept() {
        let sections = PodcastTranscriptSection.sections(
            chapters: [
                PodcastChapter(title: "Intro", startTimeMs: 0),
                PodcastChapter(title: "Silence", startTimeMs: 10_000),
                PodcastChapter(title: "Outro", startTimeMs: 20_000),
            ],
            lines: [.init(timeInMs: 0, durationMs: 5000, text: "Only one")]
        )

        #expect(sections.count == 3)
        #expect(sections[1].rows.isEmpty)
        #expect(sections[1].chapter?.title == "Silence")
    }

    @Test("a chapter knows whether a timestamp falls inside it")
    func chapterContainsTimestamps() {
        let chapter = PodcastChapter(title: "Intro", startTimeMs: 1000)

        #expect(chapter.contains(999, nextChapterStartMs: 5000) == false)
        #expect(chapter.contains(1000, nextChapterStartMs: 5000))
        #expect(chapter.contains(4999, nextChapterStartMs: 5000))
        #expect(chapter.contains(5000, nextChapterStartMs: 5000) == false)
        #expect(chapter.contains(9999, nextChapterStartMs: nil))
    }
}
