import Foundation
@testable import Kaset
import Testing

// MARK: - PodcastTranscriptServiceTests

@Suite(.serialized, .tags(.service))
@MainActor
struct PodcastTranscriptServiceTests {
    @Test("loading publishes the episode transcript")
    func loadsTranscript() async {
        let client = MockYTMusicClient()
        client.podcastTranscripts["episode-1"] = Self.transcript
        let service = PodcastTranscriptService(client: client)

        await service.loadTranscript(for: "episode-1")

        #expect(service.transcript.lines.count == 2)
        #expect(service.transcript.languageCode == "en")
        #expect(service.transcript.isAutoGenerated)
        #expect(service.transcriptVideoId == "episode-1")
        #expect(service.isLoading == false)
        #expect(service.errorMessage == nil)
        #expect(service.hasTranscript(for: "episode-1"))
        #expect(service.hasTranscript(for: "episode-2") == false)
        #expect(client.getPodcastTranscriptVideoIds == ["episode-1"])
    }

    @Test("a loaded episode is served from the session cache")
    func reusesCache() async {
        let client = MockYTMusicClient()
        client.podcastTranscripts["episode-1"] = Self.transcript
        let service = PodcastTranscriptService(client: client)

        await service.loadTranscript(for: "episode-1")
        await service.loadTranscript(for: "episode-1")

        #expect(client.getPodcastTranscriptVideoIds == ["episode-1"])

        // Reopening the experience clears the display but not the cache.
        service.reset()
        #expect(service.transcript.isAvailable == false)

        await service.loadTranscript(for: "episode-1")
        #expect(service.transcript.isAvailable)
        #expect(client.getPodcastTranscriptVideoIds == ["episode-1"])
    }

    @Test("force refresh bypasses the cache")
    func forceRefreshRefetches() async {
        let client = MockYTMusicClient()
        client.podcastTranscripts["episode-1"] = Self.transcript
        let service = PodcastTranscriptService(client: client)

        await service.loadTranscript(for: "episode-1")
        await service.loadTranscript(for: "episode-1", forceRefresh: true)

        #expect(client.getPodcastTranscriptVideoIds == ["episode-1", "episode-1"])
    }

    @Test("a slow transcript for a previous episode never replaces the current one")
    func staleTranscriptIsDiscarded() async {
        let client = MockYTMusicClient()
        client.podcastTranscripts["episode-slow"] = Self.transcript
        client.podcastTranscripts["episode-fast"] = Self.transcript
        client.podcastTranscriptDelays["episode-slow"] = .milliseconds(150)
        let service = PodcastTranscriptService(client: client)

        // Start the slow episode first, then switch to the faster one while it is still in flight.
        let slowEpisode = Task { await service.loadTranscript(for: "episode-slow") }
        try? await Task.sleep(for: .milliseconds(25))
        await service.loadTranscript(for: "episode-fast")
        #expect(service.transcriptVideoId == "episode-fast")

        // The late result for the previous episode must not take the screen back.
        await slowEpisode.value
        #expect(service.transcriptVideoId == "episode-fast")
        #expect(service.transcript.isAvailable)
    }

    @Test("an episode without captions reports why there is no transcript")
    func unavailableTranscriptReportsMessage() async {
        let client = MockYTMusicClient()
        let service = PodcastTranscriptService(client: client)

        await service.loadTranscript(for: "episode-without-captions")

        #expect(service.transcript.isAvailable == false)
        #expect(service.transcriptVideoId == "episode-without-captions")
        #expect(service.isLoading == false)
        #expect(service.errorMessage == "No transcript is available for this episode.")
    }

    @Test("failures surface a message and stop the spinner")
    func failureReportsMessage() async {
        let client = MockYTMusicClient()
        client.shouldThrowError = YTMusicError.networkError(underlying: URLError(.notConnectedToInternet))
        let service = PodcastTranscriptService(client: client)

        await service.loadTranscript(for: "episode-1")

        #expect(service.isLoading == false)
        #expect(service.transcript.isAvailable == false)
        #expect(service.errorMessage?.isEmpty == false)
    }

    @Test("an empty video ID is ignored")
    func emptyVideoIdIsIgnored() async {
        let client = MockYTMusicClient()
        let service = PodcastTranscriptService(client: client)

        await service.loadTranscript(for: "")

        #expect(client.getPodcastTranscriptCalled == false)
        #expect(service.transcriptVideoId == nil)
    }

    // MARK: - Fixtures

    private static let transcript = PodcastTranscript(
        lines: [
            PodcastTranscriptLine(timeInMs: 0, durationMs: 6000, text: "Welcome to the show."),
            PodcastTranscriptLine(timeInMs: 6000, durationMs: 6000, text: "Today we talk about transcripts."),
        ],
        languageCode: "en",
        isAutoGenerated: true
    )
}
