import Foundation
@testable import Kaset
import Testing

// MARK: - PodcastTranscriptParserTests

@Suite(.tags(.service))
@MainActor
struct PodcastTranscriptParserTests {
    // MARK: - Caption tracks

    @Test("caption tracks are read from a player response")
    func parsesCaptionTracks() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)

        #expect(tracks.count == 3)
        #expect(tracks[0].languageCode == "de")
        #expect(tracks[0].isAutoGenerated == false)
        #expect(tracks[0].name == "Deutsch")
        #expect(tracks[0].baseURL?.absoluteString.contains("fmt=srv3") == true)
        #expect(tracks[2].languageCode == "en")
        #expect(tracks[2].isAutoGenerated)
        #expect(tracks[2].name == "English (auto-generated)")
    }

    @Test("player responses without captions yield no tracks")
    func missingCaptionsYieldNoTracks() {
        #expect(PodcastTranscriptParser.parseCaptionTracks(from: [:]).isEmpty)
        #expect(PodcastTranscriptParser.parseCaptionTracks(from: ["videoDetails": [:]]).isEmpty)
    }

    @Test("track selection prefers the requested language")
    func selectionPrefersRequestedLanguage() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)

        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "en")?.languageCode == "en")
        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "EN")?.languageCode == "en")
    }

    @Test("track selection prefers a manual track over the auto-generated one")
    func selectionPrefersManualTrack() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)

        // Both German tracks exist; the auto-generated one is listed second.
        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "de")?.isAutoGenerated == false)
    }

    @Test("track selection falls back to English, then to the first track")
    func selectionFallsBack() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)
        #expect(PodcastTranscriptParser.selectTrack(tracks, preferredLanguageCode: "fr")?.languageCode == "en")

        let germanOnly = [tracks[0]]
        #expect(PodcastTranscriptParser.selectTrack(germanOnly, preferredLanguageCode: "fr")?.languageCode == "de")
    }

    // MARK: - Timed text URL

    @Test("the timed text URL replaces the track's own format")
    func timedTextURLReplacesFormat() {
        let tracks = PodcastTranscriptParser.parseCaptionTracks(from: Self.playerResponse)
        let url = PodcastTranscriptParser.timedTextURL(for: tracks[0])

        #expect(url?.absoluteString.contains("fmt=srv3") == false)
        #expect(url?.absoluteString.contains("fmt=json3") == true)
        // Unrelated query parameters survive.
        #expect(url?.absoluteString.contains("caps=asr") == true)
        #expect(url?.absoluteString.contains("lang=de") == true)
    }

    // MARK: - Timed text payload

    @Test("timed text events become caption segments")
    func parsesTimedTextSegments() {
        let segments = PodcastTranscriptParser.parseTimedTextJSON(Self.timedTextJSON)

        #expect(segments.count == 2)
        #expect(segments[0].startMs == 0)
        #expect(segments[0].durationMs == 2000)
        #expect(segments[0].text == "This is the first\nparagraph of the episode.")
        // Events that only carry a line break are dropped.
        #expect(segments.allSatisfy { !$0.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty })
    }

    @Test("malformed timed text yields no segments")
    func malformedTimedTextYieldsNoSegments() {
        #expect(PodcastTranscriptParser.parseTimedTextJSON(Data("not json".utf8)).isEmpty)
    }

    // MARK: - Paragraph merging

    @Test("continuous cues are merged into one paragraph")
    func mergesContinuousCues() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 2000, text: "Hello and"),
            .init(startMs: 2000, durationMs: 2000, text: "welcome back"),
            .init(startMs: 4000, durationMs: 2000, text: "to the show."),
        ])

        #expect(lines.count == 1)
        #expect(lines[0].text == "Hello and welcome back to the show.")
        #expect(lines[0].timeInMs == 0)
        #expect(lines[0].durationMs == 6000)
    }

    @Test("a long silence starts a new paragraph")
    func longSilenceStartsNewParagraph() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 2000, text: "First thought."),
            .init(startMs: 5000, durationMs: 2000, text: "Second thought."),
        ])

        #expect(lines.count == 2)
        #expect(lines[0].text == "First thought.")
        #expect(lines[1].text == "Second thought.")
        #expect(lines[1].timeInMs == 5000)
    }

    @Test("long text is broken into several paragraphs")
    func longTextIsBrokenUp() {
        let cues = (0 ..< 20).map { index in
            PodcastTranscriptParser.Segment(
                startMs: index * 2000,
                durationMs: 2000,
                text: String(repeating: "word ", count: 10)
            )
        }

        let lines = PodcastTranscriptParser.mergeParagraphs(from: cues)

        #expect(lines.count > 1)
        #expect(lines.allSatisfy { !$0.text.isEmpty })
        // Cues are never split, so a paragraph can pass the ceiling by one cue (50 characters).
        #expect(lines.allSatisfy { $0.text.count <= 470 })
    }

    @Test("blank cues are ignored")
    func blankCuesAreIgnored() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 1000, text: "   "),
            .init(startMs: 1000, durationMs: 1000, text: "\n"),
            .init(startMs: 2000, durationMs: 1000, text: "Real text."),
        ])

        #expect(lines.count == 1)
        #expect(lines[0].text == "Real text.")
        #expect(lines[0].timeInMs == 2000)
    }

    @Test("caption line breaks collapse into spaces")
    func captionLineBreaksCollapse() {
        let lines = PodcastTranscriptParser.mergeParagraphs(from: [
            .init(startMs: 0, durationMs: 1000, text: "one\ntwo   three"),
        ])

        #expect(lines[0].text == "one two three")
    }

    // MARK: - Transcript lookup

    @Test("the current paragraph follows playback position")
    func currentParagraphFollowsPlayback() {
        let transcript = PodcastTranscript(lines: [
            .init(timeInMs: 0, durationMs: 5000, text: "First"),
            .init(timeInMs: 5000, durationMs: 5000, text: "Second"),
            .init(timeInMs: 10000, durationMs: 5000, text: "Third"),
        ], languageCode: "en", isAutoGenerated: true)

        #expect(transcript.currentLineIndex(atMilliseconds: 0) == 0)
        #expect(transcript.currentLineIndex(atMilliseconds: 4900) == 0)
        #expect(transcript.currentLineIndex(atMilliseconds: 5000) == 1)
        #expect(transcript.currentLineIndex(atMilliseconds: 12000) == 2)
        #expect(transcript.currentLineIndex(atMilliseconds: 20000) == nil)
        #expect(transcript.lineStatuses(at: 7000) == [.previous, .current, .upcoming])
    }

    @Test("an empty transcript is unavailable")
    func emptyTranscriptIsUnavailable() {
        #expect(PodcastTranscript.unavailable.isAvailable == false)
        #expect(PodcastTranscript.unavailable.currentLineIndex(atMilliseconds: 0) == nil)
    }

    // MARK: - Fixtures

    private static let playerResponse: [String: Any] = [
        "captions": [
            "playerCaptionsTracklistRenderer": [
                "captionTracks": [
                    [
                        "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&caps=asr&lang=de&fmt=srv3",
                        "languageCode": "de",
                        "name": ["runs": [["text": "Deutsch"]]],
                    ],
                    [
                        "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&caps=asr&lang=de&fmt=srv3",
                        "languageCode": "de",
                        "kind": "asr",
                    ],
                    [
                        "baseUrl": "https://www.youtube.com/api/timedtext?v=abc&caps=asr&lang=en&fmt=srv3",
                        "languageCode": "en",
                        "kind": "asr",
                        "name": ["runs": [["text": "English (auto-generated)"]]],
                    ],
                ],
            ],
        ],
    ]

    private static let timedTextJSON = Data(
        """
        {
          "events": [
            {
              "tStartMs": 0,
              "dDurationMs": 2000,
              "segs": [{"utf8": "This is the first\\n"}, {"utf8": "paragraph of the episode."}]
            },
            {
              "tStartMs": 2100,
              "dDurationMs": 100,
              "segs": [{"utf8": "\\n"}]
            },
            {
              "tStartMs": 2200,
              "dDurationMs": 2000,
              "segs": [{"utf8": "And a second one."}]
            }
          ]
        }
        """.utf8
    )
}
