import Foundation

// MARK: - PodcastTranscriptParser

/// Parses podcast episode transcripts from YouTube's caption data.
///
/// YouTube Music's own player client (`WEB_REMIX`) does not return caption tracks, so the
/// transcript is read from the `player` endpoint with the mobile client identity, and the
/// caption track's timed-text URL is then fetched as `fmt=json3`. See
/// [docs/adr/0017-podcast-transcript.md](../../../../docs/adr/0017-podcast-transcript.md).
enum PodcastTranscriptParser {
    /// A caption track advertised by the `player` endpoint.
    struct CaptionTrack: Equatable, Sendable {
        /// Timed-text URL for this track.
        let baseURL: URL?
        /// Language code of the track (for example `"en"`).
        let languageCode: String
        /// Human-readable track name, when the response provides one.
        let name: String?
        /// Whether this is YouTube's auto-generated track (`kind == "asr"`).
        let isAutoGenerated: Bool
    }

    /// A single caption cue (one subtitle segment).
    struct Segment: Equatable, Sendable {
        let startMs: Int
        let durationMs: Int
        let text: String
    }

    /// Paragraph shaping rules for merged cues.
    private enum Paragraph {
        /// A silence longer than this starts a new paragraph.
        static let pauseBreakMs = 1200
        /// Target paragraph length; longer text may still be merged across short gaps.
        static let preferredLength = 240
        /// Once a paragraph is this long, the next cue starts a new one — cues are never split,
        /// so a paragraph can exceed this by one cue's length.
        static let maximumLength = 420
    }

    // MARK: - Caption tracks

    /// Extracts the caption tracks from a `player` response.
    static func parseCaptionTracks(from playerResponse: [String: Any]) -> [CaptionTrack] {
        guard let captions = playerResponse["captions"] as? [String: Any],
              let tracklist = captions["playerCaptionsTracklistRenderer"] as? [String: Any],
              let tracks = tracklist["captionTracks"] as? [[String: Any]]
        else {
            return []
        }

        return tracks.compactMap { track in
            guard let languageCode = track["languageCode"] as? String else { return nil }

            let name = (track["name"] as? [String: Any])
                .flatMap { $0["runs"] as? [[String: Any]] }?
                .compactMap { $0["text"] as? String }
                .joined()

            return CaptionTrack(
                baseURL: (track["baseUrl"] as? String).flatMap(URL.init(string:)),
                languageCode: languageCode,
                name: name?.isEmpty == false ? name : nil,
                isAutoGenerated: (track["kind"] as? String) == "asr"
            )
        }
    }

    /// Picks the best available track: the preferred language wins, and within one language a
    /// manually created track beats YouTube's auto-generated one.
    static func selectTrack(_ tracks: [CaptionTrack], preferredLanguageCode: String?) -> CaptionTrack? {
        let preferred = preferredLanguageCode?.lowercased()

        if let preferred, let match = bestTrack(in: tracks.filter { $0.languageCode.lowercased() == preferred }) {
            return match
        }

        if let english = bestTrack(in: tracks.filter { $0.languageCode.lowercased().hasPrefix("en") }) {
            return english
        }

        return self.bestTrack(in: tracks)
    }

    private static func bestTrack(in tracks: [CaptionTrack]) -> CaptionTrack? {
        tracks.first(where: { !$0.isAutoGenerated && $0.baseURL != nil })
            ?? tracks.first(where: { $0.baseURL != nil })
            ?? tracks.first
    }

    /// Builds the timed-text URL for a track in the requested format.
    ///
    /// The track URL ships its own `fmt` value and ignores a second one, so the existing
    /// value has to be replaced rather than appended to.
    static func timedTextURL(for track: CaptionTrack, format: String = "json3") -> URL? {
        guard let baseURL = track.baseURL?.absoluteString else { return nil }

        let withoutFormat = baseURL.replacingOccurrences(
            of: "&fmt=[^&]*",
            with: "",
            options: .regularExpression
        )
        let separator = withoutFormat.contains("?") ? "&" : "?"
        return URL(string: "\(withoutFormat)\(separator)fmt=\(format)")
    }

    // MARK: - Timed text

    /// Parses a timed-text `json3` payload into caption segments.
    static func parseTimedTextJSON(_ data: Data) -> [Segment] {
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let events = json["events"] as? [[String: Any]]
        else {
            return []
        }

        return events.compactMap { event in
            guard let segments = event["segs"] as? [[String: Any]] else { return nil }

            let text = segments.compactMap { $0["utf8"] as? String }.joined()
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }

            let startMs = event["tStartMs"] as? Int ?? Int(event["tStartMs"] as? Double ?? 0)
            let durationMs = event["dDurationMs"] as? Int ?? Int(event["dDurationMs"] as? Double ?? 0)

            return Segment(startMs: startMs, durationMs: durationMs, text: text)
        }
    }

    /// Merges caption cues into readable transcript paragraphs.
    static func mergeParagraphs(from segments: [Segment]) -> [PodcastTranscriptLine] {
        var lines: [PodcastTranscriptLine] = []
        var currentText = ""
        var currentStartMs = 0
        var currentEndMs = 0

        func flush() {
            let text = currentText.trimmingCharacters(in: .whitespacesAndNewlines)
            if !text.isEmpty {
                lines.append(
                    PodcastTranscriptLine(
                        timeInMs: currentStartMs,
                        durationMs: max(0, currentEndMs - currentStartMs),
                        text: text
                    )
                )
            }
            currentText = ""
        }

        for segment in segments {
            let text = self.normalize(segment.text)
            guard !text.isEmpty else { continue }

            let gap = segment.startMs - currentEndMs
            let startsNewParagraph = !currentText.isEmpty && (
                gap > Paragraph.pauseBreakMs
                    || currentText.count >= Paragraph.maximumLength
                    || (currentText.count >= Paragraph.preferredLength && gap > 0)
            )

            if startsNewParagraph {
                flush()
            }

            if currentText.isEmpty {
                currentStartMs = segment.startMs
            } else {
                currentText += " "
            }

            currentText += text
            currentEndMs = segment.startMs + segment.durationMs
        }

        flush()
        return lines
    }

    /// Builds a transcript from a `player` response and its timed-text payload.
    static func transcript(
        from playerResponse: [String: Any],
        timedTextJSON: Data,
        preferredLanguageCode: String?
    ) -> PodcastTranscript {
        let tracks = self.parseCaptionTracks(from: playerResponse)
        guard let track = selectTrack(tracks, preferredLanguageCode: preferredLanguageCode) else {
            return .unavailable
        }

        let lines = self.mergeParagraphs(from: self.parseTimedTextJSON(timedTextJSON))
        guard !lines.isEmpty else { return .unavailable }

        return PodcastTranscript(
            lines: lines,
            languageCode: track.languageCode,
            isAutoGenerated: track.isAutoGenerated
        )
    }

    /// Collapses caption line breaks and repeated whitespace into single spaces.
    private static func normalize(_ text: String) -> String {
        text
            .replacingOccurrences(of: "\u{00A0}", with: " ")
            .split(whereSeparator: { $0.isWhitespace })
            .joined(separator: " ")
    }
}
